-- MySQL Script generated by MySQL Workbench
-- Mon Dec  9 21:34:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `customerID` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `DOB` DATE NOT NULL,
  `CNIC` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  `joining_date` DATE NOT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `customerID_UNIQUE` (`customerID` ASC) ,
  UNIQUE INDEX `CNIC_UNIQUE` (`CNIC` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `empID` INT NOT NULL AUTO_INCREMENT,
  `first_ name` VARCHAR(25) NOT NULL,
  `last_name` VARCHAR(25) NOT NULL,
  `gender` VARCHAR(6) NOT NULL,
  `DOB` DATE NOT NULL,
  `CNIC` VARCHAR(15) NOT NULL,
  `joinDate` DATE NOT NULL,
  `salary` INT NOT NULL,
  `branchID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`empID`),
  UNIQUE INDEX `empID_UNIQUE` (`empID` ASC) ,
  UNIQUE INDEX `CNIC_UNIQUE` (`CNIC` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `empID` INT NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  INDEX `fk_Admin_Employee_idx` (`empID` ASC) ,
  CONSTRAINT `fk_Admin_Employee`
    FOREIGN KEY (`empID`)
    REFERENCES `mydb`.`Employee` (`empID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receptionist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Receptionist` (
  `empID` INT NOT NULL,
  `password` VARCHAR(25) NOT NULL,
  INDEX `fk_Receptionist_Employee1_idx` (`empID` ASC) ,
  CONSTRAINT `fk_Receptionist_Employee1`
    FOREIGN KEY (`empID`)
    REFERENCES `mydb`.`Employee` (`empID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Phone` (
  `customerID` INT NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  INDEX `fk_Customer_Phone_Customer1_idx` (`customerID` ASC) ,
  CONSTRAINT `fk_Customer_Phone_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee_Phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee_Phone` (
  `empID` INT NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  INDEX `fk_Employee_Phone_Employee1_idx` (`empID` ASC) ,
  CONSTRAINT `fk_Employee_Phone_Employee1`
    FOREIGN KEY (`empID`)
    REFERENCES `mydb`.`Employee` (`empID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `countryID` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`countryID`),
  UNIQUE INDEX `countryID_UNIQUE` (`countryID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `cityID` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(35) NOT NULL,
  `countryID` INT NOT NULL,
  PRIMARY KEY (`cityID`),
  UNIQUE INDEX `cityID_UNIQUE` (`cityID` ASC) ,
  INDEX `fk_City_Country1_idx` (`countryID` ASC) ,
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`countryID`)
    REFERENCES `mydb`.`Country` (`countryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NOT NULL,
  `City_cityID` INT NOT NULL,
  PRIMARY KEY (`addressID`),
  UNIQUE INDEX `addressID_UNIQUE` (`addressID` ASC) ,
  INDEX `fk_Address_City1_idx` (`City_cityID` ASC) ,
  CONSTRAINT `fk_Address_City1`
    FOREIGN KEY (`City_cityID`)
    REFERENCES `mydb`.`City` (`cityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Address` (
  `addressID` INT NOT NULL,
  `customerID` INT NOT NULL,
  PRIMARY KEY (`addressID`, `customerID`),
  INDEX `fk_Address_has_Customer_Customer1_idx` (`customerID` ASC) ,
  INDEX `fk_Address_has_Customer_Address1_idx` (`addressID` ASC) ,
  CONSTRAINT `fk_Address_has_Customer_Address1`
    FOREIGN KEY (`addressID`)
    REFERENCES `mydb`.`Address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_has_Customer_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address_has_Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Address_has_Employee` (
  `addressID` INT NOT NULL,
  `empID` INT NOT NULL,
  PRIMARY KEY (`addressID`, `empID`),
  INDEX `fk_Address_has_Employee_Employee1_idx` (`empID` ASC) ,
  INDEX `fk_Address_has_Employee_Address1_idx` (`addressID` ASC) ,
  CONSTRAINT `fk_Address_has_Employee_Address1`
    FOREIGN KEY (`addressID`)
    REFERENCES `mydb`.`Address` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Address_has_Employee_Employee1`
    FOREIGN KEY (`empID`)
    REFERENCES `mydb`.`Employee` (`empID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `typeID` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`typeID`),
  UNIQUE INDEX `typeID_UNIQUE` (`typeID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee_Type` (
  `empID` INT NOT NULL,
  `typeID` INT NOT NULL,
  PRIMARY KEY (`empID`, `typeID`),
  INDEX `fk_Employee_has_Type_Type1_idx` (`typeID` ASC) ,
  INDEX `fk_Employee_has_Type_Employee1_idx` (`empID` ASC) ,
  CONSTRAINT `fk_Employee_has_Type_Employee1`
    FOREIGN KEY (`empID`)
    REFERENCES `mydb`.`Employee` (`empID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Type_Type1`
    FOREIGN KEY (`typeID`)
    REFERENCES `mydb`.`Type` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `locationID` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  `cityID` INT NOT NULL,
  PRIMARY KEY (`locationID`),
  UNIQUE INDEX `locationID_UNIQUE` (`locationID` ASC) ,
  INDEX `fk_Location_City1_idx` (`cityID` ASC) ,
  CONSTRAINT `fk_Location_City1`
    FOREIGN KEY (`cityID`)
    REFERENCES `mydb`.`City` (`cityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Branch` (
  `branchID` INT NOT NULL AUTO_INCREMENT,
  `branch_name` VARCHAR(25) NOT NULL,
  `locationID` INT NOT NULL,
  PRIMARY KEY (`branchID`),
  UNIQUE INDEX `branchID_UNIQUE` (`branchID` ASC) ,
  INDEX `fk_Branch_Location1_idx` (`locationID` ASC) ,
  CONSTRAINT `fk_Branch_Location1`
    FOREIGN KEY (`locationID`)
    REFERENCES `mydb`.`Location` (`locationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`House`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`House` (
  `houseID` INT NOT NULL AUTO_INCREMENT,
  `huose_Type` VARCHAR(25) NOT NULL,
  `branchID` INT NOT NULL,
  PRIMARY KEY (`houseID`),
  UNIQUE INDEX `houseID_UNIQUE` (`houseID` ASC) ,
  INDEX `fk_House_Branch1_idx` (`branchID` ASC) ,
  CONSTRAINT `fk_House_Branch1`
    FOREIGN KEY (`branchID`)
    REFERENCES `mydb`.`Branch` (`branchID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room` (
  `roomID` INT NOT NULL AUTO_INCREMENT,
  `room_number` VARCHAR(5) NOT NULL,
  `houseID` INT NOT NULL,
  PRIMARY KEY (`roomID`),
  UNIQUE INDEX `roomID_UNIQUE` (`roomID` ASC) ,
  INDEX `fk_Room_House1_idx` (`houseID` ASC) ,
  CONSTRAINT `fk_Room_House1`
    FOREIGN KEY (`houseID`)
    REFERENCES `mydb`.`House` (`houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Services` (
  `serviceID` INT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(25) NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`serviceID`),
  UNIQUE INDEX `serviceID_UNIQUE` (`serviceID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bills` (
  `customerID` INT NOT NULL,
  `serviceID` INT NOT NULL,
  PRIMARY KEY (`customerID`, `serviceID`),
  INDEX `fk_Customer_has_Services_Services1_idx` (`serviceID` ASC) ,
  INDEX `fk_Customer_has_Services_Customer1_idx` (`customerID` ASC) ,
  CONSTRAINT `fk_Customer_has_Services_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Services_Services1`
    FOREIGN KEY (`serviceID`)
    REFERENCES `mydb`.`Services` (`serviceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Record` (
  `customerID` INT NOT NULL,
  `booking` VARCHAR(5) NOT NULL,
  `booking_date` DATE NOT NULL,
  `leaving_date` DATE NOT NULL,
  INDEX `fk_Customer_Record_Customer1_idx` (`customerID` ASC) ,
  CONSTRAINT `fk_Customer_Record_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmpoyeeLeft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EmpoyeeLeft` (
  `empID` INT NOT NULL,
  `leaving_date` DATE NOT NULL,
  INDEX `fk_EmpoyeeLeft_Employee1_idx` (`empID` ASC) ,
  CONSTRAINT `fk_EmpoyeeLeft_Employee1`
    FOREIGN KEY (`empID`)
    REFERENCES `mydb`.`Employee` (`empID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer_Deleted`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customer_Deleted` (
  `customerID` INT NOT NULL,
  `joining_date` DATE NOT NULL,
  `leaving_date` DATE NOT NULL,
  INDEX `fk_Customer_Deleted_Customer1_idx` (`customerID` ASC) ,
  CONSTRAINT `fk_Customer_Deleted_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Service_Record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Service_Record` (
  `serviceID` INT NOT NULL,
  `customerID` INT NOT NULL,
  `empID` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` VARCHAR(45) NOT NULL,
  INDEX `fk_Service_Record_Services1_idx` (`serviceID` ASC) ,
  INDEX `fk_Service_Record_Customer1_idx` (`customerID` ASC) ,
  INDEX `fk_Service_Record_Employee1_idx` (`empID` ASC) ,
  CONSTRAINT `fk_Service_Record_Services1`
    FOREIGN KEY (`serviceID`)
    REFERENCES `mydb`.`Services` (`serviceID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Record_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Service_Record_Employee1`
    FOREIGN KEY (`empID`)
    REFERENCES `mydb`.`Employee` (`empID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`House_Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`House_Booking` (
  `houseID` INT NOT NULL,
  `customerID` INT NOT NULL,
  INDEX `fk_House_Booking_House1_idx` (`houseID` ASC) ,
  INDEX `fk_House_Booking_Customer1_idx` (`customerID` ASC) ,
  CONSTRAINT `fk_House_Booking_House1`
    FOREIGN KEY (`houseID`)
    REFERENCES `mydb`.`House` (`houseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_House_Booking_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Room_Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Room_Booking` (
  `roomID` INT NOT NULL,
  `customerID` INT NOT NULL,
  INDEX `fk_Room_Booking_Room1_idx` (`roomID` ASC) ,
  INDEX `fk_Room_Booking_Customer1_idx` (`customerID` ASC) ,
  CONSTRAINT `fk_Room_Booking_Room1`
    FOREIGN KEY (`roomID`)
    REFERENCES `mydb`.`Room` (`roomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Room_Booking_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complaint_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complaint_Category` (
  `complaintCategoryID` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`complaintCategoryID`),
  UNIQUE INDEX `complaintCategoryID_UNIQUE` (`complaintCategoryID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complaint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complaint` (
  `complaintID` INT NOT NULL AUTO_INCREMENT,
  `complaintCategoryID` INT NOT NULL,
  `complaint` VARCHAR(100) NOT NULL,
  `customerID` INT NOT NULL,
  PRIMARY KEY (`complaintID`),
  UNIQUE INDEX `complaintID_UNIQUE` (`complaintID` ASC) ,
  INDEX `fk_Complaint_Complaint_Category1_idx` (`complaintCategoryID` ASC) ,
  INDEX `fk_Complaint_Customer1_idx` (`customerID` ASC) ,
  CONSTRAINT `fk_Complaint_Complaint_Category1`
    FOREIGN KEY (`complaintCategoryID`)
    REFERENCES `mydb`.`Complaint_Category` (`complaintCategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Complaint_Customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `mydb`.`Customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Response` (
  `responseID` INT NOT NULL AUTO_INCREMENT,
  `response` VARCHAR(100) NOT NULL,
  `complaintID` INT NOT NULL,
  PRIMARY KEY (`responseID`),
  UNIQUE INDEX `responseID_UNIQUE` (`responseID` ASC) ,
  INDEX `fk_Response_Complaint1_idx` (`complaintID` ASC) ,
  CONSTRAINT `fk_Response_Complaint1`
    FOREIGN KEY (`complaintID`)
    REFERENCES `mydb`.`Complaint` (`complaintID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
